### ISSUE TITLE
iGen can support it？

### ISSUE THREAD

**Issue by birdmichael** [tuan188/CleanArchitecture#2]

**Comment by tuanta-0175** [comment]
Sure, but it may take a while before I plan to do it.

**Comment by tuan188** [comment]
Sure, but it may take a while before I plan to do it.

**Comment by birdmichael** [comment]
come on.

I'm learning your clean architecture recently, but it's easy to confuse now.

**Comment by birdmichael** [comment]
```
let vc: ReposViewController = assembler.resolve(navigationController: nav)
let vc: MainViewController = assembler.resolve(navigationController: nav)
```
Isn't it a better way to use type derivation?
Is there any better way?

**Comment by tuan188** [comment]
You can rename the resolve function in the assembler to something else.
